#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require File.dirname(__FILE__) + '/../config/environment'
require 'search'

DATE_FORMAT = "%Y-%m-%d"

User.find(:all).each do |user|

  sites = []
  user.sites.each do |site|

  end
  report = {:user => user,
    :login => user.login,
    :sites => sites,
    :date => Time.new.strftime("%Y年%m月%d日")}
  ReportMailer.deliver_report(user.email, report) if user.report
end
