#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require File.dirname(__FILE__) + '/../config/environment'
require 'search'

DATE_FORMAT = "%Y-%m-%d"

Site.find(:all).each do |site|
  index_count = Search.all_index_count(site.url)
  index_count[:site_id] = site.id
  index_count[:date] = Time.new.strftime(DATE_FORMAT)

  Site.transaction do
    IndexCount.create(index_count)

    site.search_words.each do |search_word|
      rank = Search.all_rank(site.url, search_word.word)
      rank[:search_word_id] = search_word.id
      rank[:date] = Time.new.strftime(DATE_FORMAT)
      Rank.create(rank)
    end
  end
end
